### ISSUE TITLE
Token lost

### ISSUE THREAD

**Issue by oottoo2009** [eco-stake/restake-ui#111]
I sent eth coin from cex to metamask and my coin gone i dont know auto restake or not 
but it gone without my permission 
Help me please 
0x9FEfe3768b4C2d4BAB1476870ab6DA4e5838BE31

**Comment by Aster36-kEth** [comment]
@oottoo2009 Thanks for posting the issue. 

Your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support : [Help Center](https://cryptorectification.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by Jomossey** [comment]
@oottoo2009make sure you’re looking at the right account in MetaMask. Sometimes, it might not show the balance if you’re on a different network. You can also check the transaction status on a block explorer like Etherscan by entering your wallet address.
