### ISSUE TITLE
Failed to redelegate stake on Medas Digital

### ISSUE THREAD

**Issue by dr-leevsey** [eco-stake/restake-ui#121]
<img width="792" alt="image" src="https://github.com/user-attachments/assets/f38f7583-c436-4bf6-a118-136324d36a95" />

**Comment by tombeynon** [comment]
As the error shows, you need to wait for the previous redelegation to complete first.

**Comment by dr-leevsey** [comment]
> As the error shows, you need to wait for the previous redelegation to complete first.

well, I can read man
sorry I wasn't detailed enough - there's no re-delegation in progress (or there's some re-delegation that stuck forever, it's there for at least one month)

**Comment by tombeynon** [comment]
Strange. Can you send me the chain and your wallet address (either here or email me on tom@ecostake.com) and I'll take a look.
