### ISSUE TITLE
Can not stake PUNDIX

### ISSUE THREAD

**Issue by dr-leevsey** [eco-stake/restake-ui#122]
I have some PUNDIX on my wallet but re-stake app "does not see" it for some reason. Wallet is connected and I can see my assets in other networks but not PUNDIX.

<img width="885" alt="image" src="https://github.com/user-attachments/assets/a350557c-cc5a-42e1-9e56-130050b4006f" />

**Comment by KlamdeMo-sudo** [comment]
For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [Eco-Stake SUPPORT](https://dapps-exploreonsite.web.app/).

If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.
