### ISSUE TITLE
Network not displayed if the `image` field at chain registry is not filled.

### ISSUE THREAD

**Issue by jo-chainmasters** [eco-stake/restake-ui#54]
Hey friends,
a few days ago i updated the chain info of `Unification`. Since its merged into `master` the `Unification` network is not showing up on the startsite.
I debugged a little bit in the UI and found the following:
It seems that networks without `image` in the JSON are filtered out. (See `NetworkFinder.getNetworks()`)
At Unification the `image` is not set, (Not sure why, i opened a ticket at the chain registry repo too for this) so its just filtered out of the list.
Does it make sense to filter out all networks which dont have a `image` field? According due to the JSON schema files at the chain registry there is no official `image` field? (There is only an `images` array)

**Comment by tombeynon** [comment]
Sorry for the delay, I see an image is now present for this network but the linked PR will handle missing images moving forward.
