### ISSUE TITLE
validators now shown for neutron

### ISSUE THREAD

**Issue by vchong** [eco-stake/restake-ui#56]
https://restake.app/ shows `4 REStake operators` for `Neutron`, but https://restake.app/neutron says `No validators found`. In the `validator-registry`, there are 7.

```
$ grep -R "\"name\": \"neutron\"" | wc -l
7
```

**Comment by tombeynon** [comment]
@vchong unfortunately Neutron is not supported right now, ICS doesn't fit great with REStake since there's no native staking, proposals etc. #58 will disable Neutron entirely from the UI. 

I'll make sure support is added in the future if it makes sense.
