### ISSUE TITLE
Could not connect to any available API servers

### ISSUE THREAD

**Issue by seboly** [eco-stake/restake-ui#79]
Hi, 

Problem to connect API servers.
I had 600 sources and now nothing. No more validators. How do I get them back?
Thanks
Sebastian
![Source](https://github.com/eco-stake/restake-ui/assets/152878808/22005949-0cfa-40a0-bbd2-54c9716ea824)

**Comment by tombeynon** [comment]
If this kind of error occurs, you should be able to re-connect by refreshing. REStake relies on public nodes for many chains.
