### ISSUE TITLE
Trouble sending Odin tokens from Osmosis 'assets' to Staking wallet

### ISSUE THREAD

**Issue by chucky008** [eco-stake/restake-ui#87]
Having trouble sending Odin tokens to my kepler extension wallet. 
It's very consistent and I have made many attempts in the past few Weeks.
There was never any problems with this before!

Here is the error msg:   
TRANSACTION FAILED
recieving chain block height>=packet
timeout height (012895730>=0-
11805249) {packet timeout cosmos/ibc
go/v7@v7.3.1/modules/core/04-
channel/keeper/packet.go:81} With gas
wanted: '300000000' and gas used:
'163722' (at msg 0)

**Comment by tombeynon** [comment]
Is this on REStake or Osmosis? Closing for now, re-open if this is an issue with the REStake website.
