### ISSUE TITLE
Terra classic: Failed to broadcast

### ISSUE THREAD

**Issue by Sigfrodr** [eco-stake/restake-ui#89]
Message error when using restake with Terra classic: 
Failed to broadcast: Unable to sign message with this wallet/signer

Tried with differents wallets, same problem.

**Comment by BullBoss5** [comment]
Getting same error

![Screenshot from 2024-04-08 11-27-18](https://github.com/eco-stake/restake-ui/assets/155774118/1e543fe0-2160-4d9d-90e2-6c3d0a80cedb)

**Comment by tombeynon** [comment]
This should be resolved, other than #101. Please re-open if you still have problems.

**Comment by Sigfrodr** [comment]
@tombeynon Still not working.

**Comment by Liiw** [comment]
I have found myself in a similar situation.

`Failed to broadcast: Error when broadcasting tx 4FD23A426FA4FB3A0FC80CC5E4A90F07B5DC4F8EF31CE77BFC87A3A84FB4F7C9 at height 0. Code: 4; Raw log: signature verification failed; please verify account number (5051527), sequence (12) and chain-id (columbus-5): unauthorized`

Is this issue similar to the accountNumber 0 bug that has appeared on other chains?

For example: [#638](https://github.com/eco-stake/restake/issues/638)

**Comment by tombeynon** [comment]
This appears to be a problem with the StakeAuthorisation grant we use to enable auto-compounding. The conversion from amino logic is missing in Terra.js. I've raised https://github.com/terra-money/terra.js/issues/367 to find the best solution.
