### ISSUE TITLE
Unable to Restake

### ISSUE THREAD

**Issue by maqboolahmedm** [eco-stake/restake-ui#91]
![Screenshot_2024-03-20-00-21-55-72_ea2b19a9c2013444f66ccaa4e767877d](https://github.com/eco-stake/restake-ui/assets/127714459/a96617ae-a4dc-43be-bca4-daeda216a36b)
![Screenshot_2024-03-20-00-22-05-74_ea2b19a9c2013444f66ccaa4e767877d](https://github.com/eco-stake/restake-ui/assets/127714459/a0a3196f-c99b-4f5b-a23e-d997ce1bf85e)

**Comment by tombeynon** [comment]
This should be resolved now
